server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This will first try the file exactly as is (e.g. /shop.html)
        # Then it will try adding .html (e.g. /shop -> /shop.html)
        # Then it will try it as a directory
        # Finally it will fallback to index.html
        try_files $uri $uri.html $uri/ /index.html;
    }

    # API Proxy
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
